// Writes the ABIs the web app needs as typed `as const` modules, so viem can
// infer argument and event types. Run after `hardhat compile`.
const fs = require("node:fs");
const path = require("node:path");

const ARTIFACTS = path.join(__dirname, "../artifacts/src");
const OUT = path.join(__dirname, "../../web/src/lib/abi.ts");
const CONTRACTS = [
  ["maweePoolAbi", "MaweePool.sol/MaweePool.json"],
  ["maweeRegistryAbi", "MaweeRegistry.sol/MaweeRegistry.json"],
];

const erc20Abi = `[
  { type: "function", name: "balanceOf", stateMutability: "view", inputs: [{ name: "owner", type: "address" }], outputs: [{ name: "", type: "uint256" }] },
  { type: "function", name: "allowance", stateMutability: "view", inputs: [{ name: "owner", type: "address" }, { name: "spender", type: "address" }], outputs: [{ name: "", type: "uint256" }] },
  { type: "function", name: "approve", stateMutability: "nonpayable", inputs: [{ name: "spender", type: "address" }, { name: "amount", type: "uint256" }], outputs: [{ name: "", type: "bool" }] },
  { type: "function", name: "transfer", stateMutability: "nonpayable", inputs: [{ name: "to", type: "address" }, { name: "amount", type: "uint256" }], outputs: [{ name: "", type: "bool" }] },
  { type: "function", name: "mint", stateMutability: "nonpayable", inputs: [{ name: "to", type: "address" }, { name: "amount", type: "uint256" }], outputs: [] },
  { type: "function", name: "name", stateMutability: "view", inputs: [], outputs: [{ name: "", type: "string" }] },
  { type: "function", name: "version", stateMutability: "view", inputs: [], outputs: [{ name: "", type: "string" }] },
  { type: "function", name: "nonces", stateMutability: "view", inputs: [{ name: "owner", type: "address" }], outputs: [{ name: "", type: "uint256" }] },
  { type: "function", name: "eip712Domain", stateMutability: "view", inputs: [], outputs: [{ name: "fields", type: "bytes1" }, { name: "name", type: "string" }, { name: "version", type: "string" }, { name: "chainId", type: "uint256" }, { name: "verifyingContract", type: "address" }, { name: "salt", type: "bytes32" }, { name: "extensions", type: "uint256[]" }] },
]`;

let out = "// Generated by contracts/scripts/export-abis.cjs — do not edit by hand.\n\n";
for (const [name, file] of CONTRACTS) {
  const { abi } = JSON.parse(fs.readFileSync(path.join(ARTIFACTS, file), "utf8"));
  out += `export const ${name} = ${JSON.stringify(abi, null, 2)} as const;\n\n`;
}
out += `/** ERC-20 + EIP-2612 subset used by the app (mint exists only on the testnet MockUSDC). */\nexport const erc20Abi = ${erc20Abi} as const;\n`;
fs.writeFileSync(OUT, out);
console.log(`wrote ${path.relative(process.cwd(), OUT)}`);
