import { readFileSync, writeFileSync } from "fs";
// Run from the build dir (like to_soroban.mjs). Artifacts staged there by build.sh.
const vk = JSON.parse(readFileSync("verification_key_transfer.json"));
const proof = JSON.parse(readFileSync("proof_transfer.json"));
const pub = JSON.parse(readFileSync("public_transfer.json"));
const notes = JSON.parse(readFileSync("notes_transfer.json"));

const be32 = (dec) => BigInt(dec).toString(16).padStart(64, "0");
const G1 = (p) => be32(p[0]) + be32(p[1]); // X‖Y
const G2 = (p) => be32(p[0][1]) + be32(p[0][0]) + be32(p[1][1]) + be32(p[1][0]); // c1‖c0

let out =
  "// AUTO-GENERATED by circuits/to_soroban_transfer.mjs — snarkjs → Soroban BN254 transfer fixture.\n";
out += "// Do not edit by hand; regenerate with the circuit build.\n\n";
out += `pub const TR_VK_ALPHA: &str = "${G1(vk.vk_alpha_1)}";\n`;
out += `pub const TR_VK_BETA: &str = "${G2(vk.vk_beta_2)}";\n`;
out += `pub const TR_VK_GAMMA: &str = "${G2(vk.vk_gamma_2)}";\n`;
out += `pub const TR_VK_DELTA: &str = "${G2(vk.vk_delta_2)}";\n`;
out += `pub const TR_VK_IC: [&str; ${vk.IC.length}] = [\n`;
for (const p of vk.IC) out += `    "${G1(p)}",\n`;
out += "];\n\n";
out += `pub const TR_PROOF_A: &str = "${G1(proof.pi_a)}";\n`;
out += `pub const TR_PROOF_B: &str = "${G2(proof.pi_b)}";\n`;
out += `pub const TR_PROOF_C: &str = "${G1(proof.pi_c)}";\n`;
out += `pub const TR_PUB_SIGNALS: [&str; ${pub.length}] = [\n`;
for (const s of pub) out += `    "${be32(s)}",\n`;
out += "];\n\n";
// Note-level constants (public signal order: root, nullifier, recipientCom, changeCom).
out += `pub const TR_IN_COMMITMENT: &str = "${notes.inCommitment}";\n`;
out += `pub const TR_ROOT: &str = "${notes.root}";\n`;
out += `pub const TR_NULLIFIER: &str = "${notes.nullifier}";\n`;
out += `pub const TR_RECIPIENT_COMMITMENT: &str = "${notes.recipientCommitment}";\n`;
out += `pub const TR_CHANGE_COMMITMENT: &str = "${notes.changeCommitment}";\n`;
out += `pub const TR_IN_AMOUNT: i128 = ${notes.inAmount};\n`;
out += `pub const TR_RECIPIENT_AMOUNT: i128 = ${notes.recipientAmount};\n`;
out += `pub const TR_CHANGE_AMOUNT: i128 = ${notes.changeAmount};\n`;
writeFileSync("../../programs/olio-pool/src/transfer_fixture.rs", out);
console.log(
  "wrote transfer_fixture.rs: IC.len =",
  vk.IC.length,
  "pub.len =",
  pub.length,
);

// VK JSON for `stellar contract invoke ... set_transfer_verifier_key`.
const vkJson = {
  alpha: G1(vk.vk_alpha_1),
  beta: G2(vk.vk_beta_2),
  gamma: G2(vk.vk_gamma_2),
  delta: G2(vk.vk_delta_2),
  ic: vk.IC.map(G1),
};
writeFileSync("vk_transfer_soroban.json", JSON.stringify(vkJson));
console.log("wrote vk_transfer_soroban.json");
