import {describe,it,expect,vi} from "vitest";
import {makeReceiptFixture} from "./helpers/receiptFixtures";
import {verifyReceipt} from "../src/features/receipts/receiptVerification";
describe("anchored receipt decision",()=>{
 it("does not accept a valid self-contained proof without matching chain state",async()=>{const f=await makeReceiptFixture();const load=vi.fn().mockResolvedValue({status:"available",snapshot:{...f.snapshot,root:`0x${"33".repeat(32)}`}});expect(await verifyReceipt(f.v2,f.pool,load)).toMatchObject({status:"invalid",local:"passed",chain:"failed"});expect(load).toHaveBeenCalledWith({pool:f.pool.scope,blockNumber:100,blockHash:f.v2.anchor.blockHash});});
 it("verifies exact historical observations, but rejects pool/hash/count/token substitution",async()=>{const f=await makeReceiptFixture(),load=vi.fn().mockResolvedValue({status:"available",snapshot:f.snapshot});expect((await verifyReceipt(f.v2,f.pool,load)).status).toBe("verified");for(const change of [{pool:`31337:0x${"1".repeat(40)}`},{blockHash:`0x${"22".repeat(32)}`},{leafCount:2},{token:`0x${"9".repeat(40)}`},{tokenDecimals:7}]){load.mockResolvedValue({status:"available",snapshot:{...f.snapshot,...change}});expect((await verifyReceipt(f.v2,f.pool,load)).status).toBe("invalid");}});
 it("never queries for invalid math or unanchored v1",async()=>{const f=await makeReceiptFixture("USDC"),load=vi.fn();expect((await verifyReceipt({...f.v2,salt:"8"},f.pool,load)).status).toBe("invalid");expect(await verifyReceipt(f.v1,f.pool,load)).toMatchObject({status:"unavailable",local:"passed",reason:"anchor-missing"});expect(load).not.toHaveBeenCalled();});
 it("keeps outages, cancellation and low confirmations separate from invalid proofs",async()=>{const f=await makeReceiptFixture(),load=vi.fn().mockRejectedValue(new Error("PRIVATE_RPC_URL"));expect(JSON.stringify(await verifyReceipt(f.v2,f.pool,load))).not.toContain("PRIVATE_RPC_URL");load.mockResolvedValue({status:"available",snapshot:{...f.snapshot,confirmed:false}});expect((await verifyReceipt(f.v2,f.pool,load)).status).toBe("unavailable");load.mockClear();expect((await verifyReceipt(f.v2,f.pool,load,()=>false)).status).toBe("unavailable");expect(load).not.toHaveBeenCalled();});
});
