import {describe,it,expect,vi} from "vitest";
import {makeReceiptFixture} from "./helpers/receiptFixtures";
import {readReceiptChainSnapshot,withReceiptSnapshotLimit,type ReceiptRpcReader} from "../src/server/modules/receipts/receipts.service";
import type {ReceiptChainOutcome} from "../src/features/receipts/receiptChainTypes";
describe("public historical receipt snapshot",()=>{
 it("keeps slots occupied after a deadline until the underlying work settles",async()=>{vi.useFakeTimers();const release:Array<(outcome:ReceiptChainOutcome)=>void>=[];try{const pending=Array.from({length:8},()=>withReceiptSnapshotLimit(()=>new Promise(r=>release.push(r)),1));await vi.advanceTimersByTimeAsync(2);expect((await Promise.all(pending)).every(x=>x.status==="unavailable"&&x.reason==="rpc-timeout")).toBe(true);expect(await withReceiptSnapshotLimit(async()=>({status:"unavailable",reason:"completed"}))).toEqual({status:"unavailable",reason:"busy"});release.forEach(r=>r({status:"unavailable",reason:"completed"}));await Promise.resolve();await Promise.resolve();await Promise.resolve();expect(await withReceiptSnapshotLimit(async()=>({status:"unavailable",reason:"completed"}))).toEqual({status:"unavailable",reason:"completed"});}finally{release.forEach(r=>r({status:"unavailable",reason:"completed"}));vi.useRealTimers();}});
 async function fixture(){const f=await makeReceiptFixture();const reader={chainId:vi.fn().mockResolvedValue(31337),head:vi.fn().mockResolvedValue(105),block:vi.fn().mockResolvedValue({number:100,hash:f.snapshot.blockHash}),root:vi.fn().mockResolvedValue(f.snapshot.root),leafCount:vi.fn().mockResolvedValue(1),token:vi.fn().mockResolvedValue(f.pool.token),decimals:vi.fn().mockResolvedValue(6)} satisfies ReceiptRpcReader;return {f,reader,deps:{reader,resolve:(s:string)=>s===f.pool.scope?f.pool:null,chainId:31337},input:{pool:f.pool.scope,blockNumber:100,blockHash:f.snapshot.blockHash}};}
 it("uses historical state at one canonical block",async()=>{const {f,reader,deps,input}=await fixture();expect(await readReceiptChainSnapshot(input,deps)).toEqual({status:"available",snapshot:f.snapshot});expect(reader.root).toHaveBeenCalledWith(f.pool,100);expect(reader.block).toHaveBeenCalledTimes(2);});
 it("does not mix reorg states or expose a raw RPC error",async()=>{const {reader,deps,input}=await fixture();reader.block.mockResolvedValueOnce({number:100,hash:input.blockHash}).mockResolvedValueOnce({number:100,hash:`0x${"22".repeat(32)}`});expect(await readReceiptChainSnapshot(input,deps)).toEqual({status:"unavailable",reason:"reorg-during-read"});reader.block.mockRejectedValue(new Error("https://secret-rpc/key"));expect(JSON.stringify(await readReceiptChainSnapshot(input,deps))).not.toContain("secret-rpc");});
 it("refuses unknown scopes before RPC and detects token/hash mismatch",async()=>{const {reader,deps,input}=await fixture();expect((await readReceiptChainSnapshot({...input,pool:`31337:0x${"9".repeat(40)}`},deps)).status).toBe("unavailable");expect(reader.chainId).not.toHaveBeenCalled();reader.token.mockResolvedValue(`0x${"9".repeat(40)}`);expect((await readReceiptChainSnapshot(input,deps)).status).toBe("mismatch");reader.token.mockReset();});
 it("distinguishes insufficient confirmations and accepts legacy pools",async()=>{const {f,reader,deps,input}=await fixture();reader.head.mockResolvedValue(100);const legacy={...f.pool,role:"legacy" as const,confirmations:2};expect((await readReceiptChainSnapshot(input,{...deps,resolve:()=>legacy})).status).toBe("unavailable");reader.head.mockResolvedValue(105);expect((await readReceiptChainSnapshot(input,{...deps,resolve:()=>legacy})).status).toBe("available");});
});
