import {readFileSync,existsSync} from "node:fs";
import {fileURLToPath} from "node:url";
import {it,expect} from "vitest";
import type {PoolDescriptor} from "../src/lib/pools";
import type {ReceiptV2} from "../src/features/receipts/receiptTypes";
import type {ReceiptChainSnapshot} from "../src/features/receipts/receiptChainTypes";
import {parseReceiptJson} from "../src/features/receipts/receiptSchema";
import {verifyReceipt} from "../src/features/receipts/receiptVerification";
const evidence=fileURLToPath(new URL("../../.superpowers/sdd/2026-10-06-receipt-verification/real-chain-receipt.json",import.meta.url));
it.runIf(existsSync(evidence))("checks the receipt generated by real historical/spent-note contract evidence",async()=>{
 const {pool,bundle,snapshot}=JSON.parse(readFileSync(evidence,"utf8")) as {pool:PoolDescriptor;bundle:ReceiptV2;snapshot:ReceiptChainSnapshot};
 const parsed=parseReceiptJson(JSON.stringify(bundle),s=>s===pool.scope?pool:null);expect(parsed.status).toBe("parsed");
 expect((await verifyReceipt(bundle,pool,async()=>({status:"available",snapshot}))).status).toBe("verified");
 expect((await verifyReceipt({...bundle,anchor:{...bundle.anchor,blockHash:`0x${"22".repeat(32)}`}},pool,async()=>({status:"available",snapshot}))).status).toBe("invalid");
});
