// @vitest-environment happy-dom
import {render,screen,waitFor,act} from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import {beforeEach,describe,it,expect,vi} from "vitest";
import type {PoolDescriptor} from "../src/lib/pools";
const mock=vi.hoisted(()=>({pool:null as PoolDescriptor|null,query:vi.fn()}));
vi.mock("../src/lib/pools",async original=>({...await original<typeof import("../src/lib/pools")>(),findPool:(s:string)=>mock.pool?.scope===s?mock.pool:null}));
vi.mock("../src/features/receipts/receiptClient",()=>({loadReceiptSnapshot:mock.query}));
import {makeReceiptFixture} from "./helpers/receiptFixtures";
import {VerifyReceipt} from "../src/components/receipts/VerifyReceipt";
const file=(bundle:unknown)=>new File([JSON.stringify(bundle)],"receipt.json",{type:"application/json"});
describe("public receipt verifier",()=>{
 beforeEach(()=>vi.clearAllMocks());
 it("checks only public coordinates, shows identity limits, and clears the disclosure",async()=>{const f=await makeReceiptFixture();mock.pool=f.pool;mock.query.mockResolvedValue({status:"available",snapshot:f.snapshot});const user=userEvent.setup();render(<VerifyReceipt/>);await user.upload(screen.getByLabelText("Receipt JSON"),file(f.v2));await screen.findByText("Verified on chain");expect(mock.query).toHaveBeenCalledWith({pool:f.pool.scope,blockNumber:100,blockHash:f.v2.anchor.blockHash});expect(screen.getByText(/Provided by receipt issuer/)).toBeInTheDocument();await user.click(screen.getByRole("button",{name:"Remove receipt"}));expect(screen.queryByText("20 AUSD")).not.toBeInTheDocument();});
 it("cannot overwrite a replacement with an old green result",async()=>{const f=await makeReceiptFixture();mock.pool=f.pool;let resolve!:(v:unknown)=>void;mock.query.mockImplementationOnce(()=>new Promise(r=>{resolve=r;}));const user=userEvent.setup();render(<VerifyReceipt/>);const input=screen.getByLabelText("Receipt JSON");await user.upload(input,file(f.v2));await waitFor(()=>expect(mock.query).toHaveBeenCalledTimes(1));await user.upload(input,file({...f.v2,salt:"8"}));await screen.findByText("Invalid proof");await act(async()=>resolve({status:"available",snapshot:f.snapshot}));expect(screen.queryByText("Verified on chain")).not.toBeInTheDocument();});
 it("keeps v1 and RPC errors unavailable, with retry",async()=>{const f=await makeReceiptFixture("USDC");mock.pool=f.pool;const user=userEvent.setup();render(<VerifyReceipt/>);await user.upload(screen.getByLabelText("Receipt JSON"),file(f.v1));await screen.findByText("Unable to verify");expect(mock.query).not.toHaveBeenCalled();mock.query.mockRejectedValue(new Error("SECRET_RPC"));await user.upload(screen.getByLabelText("Receipt JSON"),file(f.v2));await screen.findByText(/historical/i);expect(screen.queryByText(/SECRET_RPC/)).not.toBeInTheDocument();mock.query.mockResolvedValue({status:"available",snapshot:f.snapshot});await user.click(screen.getByRole("button",{name:"Retry verification"}));await screen.findByText("Verified on chain");});
 it("rejects oversized or malformed files before transport and never persists their contents",async()=>{const f=await makeReceiptFixture();mock.pool=f.pool;const log=vi.spyOn(console,"error"),write=vi.spyOn(Storage.prototype,"setItem");const user=userEvent.setup();render(<VerifyReceipt/>);await user.upload(screen.getByLabelText("Receipt JSON"),file({...f.v2,amount:"PRIVATE_MARKER"}));await screen.findByText("Invalid proof");expect(mock.query).not.toHaveBeenCalled();expect(JSON.stringify(log.mock.calls)).not.toContain("PRIVATE_MARKER");expect(JSON.stringify(write.mock.calls)).not.toContain("PRIVATE_MARKER");await user.upload(screen.getByLabelText("Receipt JSON"),new File([" ".repeat(65_537)],"big.json",{type:"application/json"}));await screen.findByText(/too large/i);log.mockRestore();write.mockRestore();});
});
